### ISSUE TITLE
Проверить шаблон с последней версией poetry 

### ISSUE THREAD

**Issue by serykhelena** [KaiL4eK/pyproject-cookiecutter#13]
poetry v 1.2 происходят ошибки: 
1) минимальная версия Питона прописана как `~3.8` и для питона 3.9 появляется ошибка не соответствия требованиям, если заменить на `^3.8` - то всё ок 
2) на строку isort ... "^^5.3.10" в pyproject.toml поетри ругается, говорит что-то типа "не знаю такой синтаксис", если оставить одну крышечку "^5.3.10", то всё ок 
3) в файле pre-commit-config.yaml poetry ругается на первые 2 строки (при более свежей версии питона) 
default_language_version:
  python: python3.8

**Comment by KaiL4eK** [comment]
@serykhelena ты сможешь сделать PR с фиксами?

**Comment by serykhelena** [comment]
Да, я попробую сделать в ближайшее время

**Comment by KaiL4eK** [comment]
Влил в main ветку апдейт, глянь, если что-то осталось

**Comment by serykhelena** [comment]
Вроде всё норм теперь 
Закрываю issue тогда (=
