### ISSUE TITLE
Не хватает фреймворка для nbdime 

### ISSUE THREAD

**Issue by serykhelena** [KaiL4eK/pyproject-cookiecutter#15]
Падает ошибка при `make project-init`

```
ModuleNotFoundError: No module named 'ipython_genutils'
make: *** [Makefile:40: tools-install] Error 1
```

**Comment by KaiL4eK** [comment]
Это в корневом проекте или в шаблоне после создания из него? Просто, в GH Actions вроде все работает

**Comment by serykhelena** [comment]
В шаблоне, при запуске команды `make project-init`
Версия питон: 3.8

**Comment by serykhelena** [comment]
Проверила ещё раз на питоне 3.9, та же проблема

**Comment by KaiL4eK** [comment]
На Windows (домашнем и универском) не воспроизвелась проблема

**Comment by serykhelena** [comment]
Ну, возможно, это именно на моём компе что-то с зависимостями. Тогда закрывай (:
