### ISSUE TITLE
Изменить ^ на ~ для версии питона 

### ISSUE THREAD

**Issue by serykhelena** [KaiL4eK/pyproject-cookiecutter#21]
В шаблоне спрашивается какая версия питона нужна для проекта, но потом этот выбор можно сказать игнорируется 

В pyproject.toml стоит `^` вместо `~`, тогда если на компе есть несколько версий питона, то выбирается наибольшая, и если хочется, чтобы проект был с питоном 3.9, а на компе есть питон 3.10 , то окружение делается на базе питона 3.10

**Comment by KaiL4eK** [comment]
@serykhelena будет возможность сделать PR? С фиксом согласен
