### ISSUE TITLE
Добавить project-paths 

### ISSUE THREAD

**Issue by serykhelena** [KaiL4eK/pyproject-cookiecutter#27]
Чуть пощупала штуку, мне понравилось 
https://pypi.org/project/project-paths/

**Comment by KaiL4eK** [comment]
Чет меня беспокоит, что не поддерживается и звезд маловато. Я бы подумал описать подход формирования путей вместо попыток парсить pyproject. Например, в проекте всегда вводить модуль consts внутри пакета

**Comment by serykhelena** [comment]
Можно сделать свой аналог хука, как ты и написал, внутри пакета сделать paths.py, из которого дальше уже импортить в разных местах
